version: "3"

services:
  test:
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: docker/test.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # mount external docker sock
      - ..:/opt/coppyr
    tty: true
    stdin_open: true
